name: Java CI with Maven on Ubuntu & Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Maven 3.9.9
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: '3.9.9'

      - name: Set JAVA_HOME for Maven to Java 21
        run: |
          echo "JAVA_HOME=$JAVA_HOME_21_X64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME_21_X64/bin:$PATH" >> $GITHUB_ENV
          echo "JAVA_HOME is set to: $JAVA_HOME_21_X64"
          echo "PATH is updated"

      - name: Verifica variabili d'ambiente
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "PATH: $PATH"
          ls -l $JAVA_HOME/bin


      - name: Verifica versione Maven e Java
        run: |
          mvn -v
          java -version

      - name: Build con Maven
        run: mvn clean install
