name: Java CI with Maven on Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 21]

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Set up Maven 3.8.7
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: '3.8.7'

      - name: Verifica versioni Java e Maven
        run: |
          echo "JAVA VERSION:"
          java -version
          echo ""
          echo "MAVEN VERSION:"
          mvn -v

      - name: Build con Maven
        run: mvn clean install
