name: Java CI with Maven on Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 21]

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Set up Maven 3.8.7
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: '3.8.7'

      - name: setting JAVA_HOME e PATH
        run: |
          if [ "${{ matrix.java-version }}" == "21" ]; then
            export JAVA_HOME="${JAVA_HOME_21_X64}"
          elif [ "${{ matrix.java-version }}" == "8" ]; then
            export JAVA_HOME="${JAVA_HOME_8_X64}"
          fi
          export PATH="$JAVA_HOME/bin:$PATH" # senza modificare il link del binario presente nel PATH ma aggiungendo il nuovo binario
          echo "which java->"
          which java
          echo "java -version ->"
          java -version
          echo "mvn -v ->"
          mvn -v

      - name: Build con Maven
        run: mvn clean install
