name: Java CI with Maven on Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 21]

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Set up Maven 3.8.7
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: '3.8.7'
          
      - name: Impostazione JAVA_HOME e PATH
        run: |
          # Impostiamo JAVA_HOME e PATH in base alla versione di Java nel matrix
          if [ "${{ matrix.java-version }}" == "8" ]; then
            echo "JAVA_HOME=${JAVA_HOME_8_X64}" >> $GITHUB_ENV
            echo "PATH=${JAVA_HOME_8_X64}/bin:$PATH" >> $GITHUB_ENV
          elif [ "${{ matrix.java-version }}" == "21" ]; then
            echo "JAVA_HOME=${JAVA_HOME_21_X64}" >> $GITHUB_ENV
            echo "PATH=${JAVA_HOME_21_X64}/bin:$PATH" >> $GITHUB_ENV
          fi

      - name: checking java and maven versions
        run: |
          echo "which java->"
          which java
          echo "java -version ->"
          java -version
          echo "mvn -v ->"
          mvn -v

      - name: Build con Maven
        run: mvn clean install
