name: Java CI with Maven on Ubuntu & Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set JAVA_HOME on Windows
        if: runner.os == 'Windows'
        run: |
          echo "JAVA_HOME=$JAVA_HOME_21_X64" >> $GITHUB_ENV
          echo "JAVA_HOME is set to: $JAVA_HOME_21_X64"

      - name: Setup Maven 3.8.7
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: '3.9.9'

      - name: Verifica versione Maven e Java
        run: |
          mvn -v
          java -version

      - name: Build con Maven
        run: mvn clean install
